name: Update Packages
on:
  push:
    paths:
      - 'debs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate Packages
      run: |
        mkdir -p debs
        dpkg-scanpackages debs/ /dev/null > Packages
        bzip2 -kf Packages
        xz -kf Packages
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Packages*
        git commit -m "Auto-update Packages" || true
        git push
